### ISSUE TITLE
Triggering, IR filters

### ISSUE THREAD

**Issue by generalciao** [Aharoni-Lab/MiniCAM#14]
Can MiniCam be triggered by an external TTL source, so that frames are synchronized to e.g. a 2P microscope system? Along those lines, which wavelength does the IR ring use, and is it possible/easy to obtain and attach IR filters in front of the lens (for example to block ~920 nm IR light from intracranial 2P imaging)? Curious about using the MiniCam in place of more expensive options for simple pupil, whisker, paw, etc. tracking (DeeplabCut) on a 2P setup. Thanks :)

**Comment by daharoni** [comment]
Unfortunately the MiniCAM cannot currently be externally trigged on a frame by frame basis. That said, if using the Miniscope DAQ PCB and Software, you can enable external TTL triggering to start and stop recording sessions (but doesn't trigger individual frames).

The MiniCAM itself does not have any IR filtering as part of the image sensor or PCB. Any filtering you might want to do can be done by placing a thin filter right on top of the image sensor or by using M12 lenses that incorporate a filter in them.
