### ISSUE TITLE
spectral sensitivity and quantum efficiency

### ISSUE THREAD

**Issue by MariangelaP** [Aharoni-Lab/MiniCAM#15]
Hello, I'd be interested in using your miniCAM to monitor head-fixed behaviour in an operant box. Frame rate and resolution seem to be appropriate for my experiments. I just have a couple of extra questions for you. 
1) what are the dimensions of the MiniCAM?
2) what's the spectral sensitivity?
3) what's the quantum efficiency?

thank you!

**Comment by daharoni** [comment]
Hello.
1. The MiniCAM is ~25mm x 25mm and has a 1/4" - 20 threaded insert for mounting.
2. Unfortunately we do not have this information as it isn't provided in the CMOS image sensors data sheet and we haven't measured it directly ourselves. That said, it definitely has decent sensitivity up to NIR as long as you do not use an M12 lens with an IR fitler.
3. Unfortunately we do not have this information as it isn't provided in the CMOS image sensors data sheet and we haven't measured it directly ourselves.
